spring:
  profiles:
    active: local
    group:
      local: db-local
      server: db-server
    include: db

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
